# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IonicRunner
  pod 'Capacitor', '1.0.0-alpha.32'
  pod 'IonicNativePushNotifications', '0.0.3'
end

target 'PluginTests' do
  use_frameworks!

  pod 'Capacitor', '1.0.0-alpha.32'
end
